services:
  server-app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server-app
    restart: always
    networks:
      - backlogBooks
    env_file:
      - .env
    volumes:
      - ./server:/usr/source/app
      - /usr/src/app/node_modules 
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3000"

networks:
  backlogBooks:
    driver: bridge